#!/usr/bin/env sh
set -eu

PROJECT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
MODE="competition"
BIND_HOST="0.0.0.0"
PORT="8080"
DATA_DIR="${PROJECT_DIR}/data"
ADMIN_USERNAME="admin"
ADMIN_PASSWORD=""
ALLOW_INSECURE_LAN_COOKIE="false"
RUN_TESTS="false"
NO_START="false"
DRY_RUN="false"
ENV_FILE="${PROJECT_DIR}/.gateway.env"
VENV_DIR="${PROJECT_DIR}/.venv"
VENV_PYTHON="${VENV_DIR}/bin/python"

usage() {
  cat <<'EOF'
Usage: scripts/deploy-linux.sh [options]

Options:
  --mode competition|dev
  --host HOST
  --port PORT
  --data-dir DIR
  --admin-username USERNAME
  --admin-password PASSWORD
  --allow-insecure-lan-cookie
  --run-tests
  --no-start
  --dry-run
EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --mode)
      MODE="$2"
      shift 2
      ;;
    --host)
      BIND_HOST="$2"
      shift 2
      ;;
    --port)
      PORT="$2"
      shift 2
      ;;
    --data-dir)
      DATA_DIR="$2"
      shift 2
      ;;
    --admin-username)
      ADMIN_USERNAME="$2"
      shift 2
      ;;
    --admin-password)
      ADMIN_PASSWORD="$2"
      shift 2
      ;;
    --allow-insecure-lan-cookie)
      ALLOW_INSECURE_LAN_COOKIE="true"
      shift
      ;;
    --run-tests)
      RUN_TESTS="true"
      shift
      ;;
    --no-start)
      NO_START="true"
      shift
      ;;
    --dry-run)
      DRY_RUN="true"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [ "$MODE" != "competition" ] && [ "$MODE" != "dev" ]; then
  echo "--mode must be competition or dev" >&2
  exit 2
fi

generate_secret() {
  python3 - "$1" <<'PY'
import secrets
import sys

size = int(sys.argv[1])
print(secrets.token_urlsafe(size))
PY
}

env_get() {
  key="$1"
  [ -f "$ENV_FILE" ] || return 1
  while IFS= read -r line || [ -n "$line" ]; do
    case "$line" in
      "$key="*)
        printf '%s\n' "${line#*=}"
        return 0
        ;;
    esac
  done < "$ENV_FILE"
  return 1
}

write_env_file() {
  {
    echo "# Generated by scripts/deploy-linux.sh. Do not commit this file."
    echo "GATEWAY_DATA_DIR=${DATA_DIR}"
    echo "GATEWAY_BOOTSTRAP_ADMIN_USERNAME=${ADMIN_USERNAME}"
    echo "GATEWAY_BOOTSTRAP_ADMIN_PASSWORD=${ADMIN_PASSWORD}"
    echo "GATEWAY_SESSION_SECRET=${SESSION_SECRET}"
    echo "GATEWAY_CREDENTIAL_SECRET=${CREDENTIAL_SECRET}"
    echo "GATEWAY_COMPETITION_MODE=${COMPETITION_MODE}"
    echo "GATEWAY_COOKIE_SECURE=false"
    echo "GATEWAY_ALLOW_INSECURE_LAN_COOKIE=${ALLOW_INSECURE_LAN_COOKIE}"
  } > "$ENV_FILE"
}

check_python_version() {
  python3 - <<'PY'
import sys

if sys.version_info < (3, 10):
    raise SystemExit("Python 3.10 or newer is required")
PY
}

if [ "$MODE" = "competition" ] && [ "$ALLOW_INSECURE_LAN_COOKIE" != "true" ] && [ "$DRY_RUN" != "true" ]; then
  echo "Competition deployment over plain HTTP requires --allow-insecure-lan-cookie. Use HTTPS with GATEWAY_COOKIE_SECURE=true for production-grade cookie transport." >&2
  exit 2
fi

echo "DeepRacer Model Gateway deployment"
echo "Mode: ${MODE}"
echo "Project: ${PROJECT_DIR}"
echo "Env file: ${ENV_FILE}"
echo "Data dir: ${DATA_DIR}"
echo "Virtualenv: ${VENV_DIR}"
echo "User URL: http://${BIND_HOST}:${PORT}/login"
echo "Admin URL: http://${BIND_HOST}:${PORT}/admin/login"

if [ "$DRY_RUN" = "true" ]; then
  echo "Dry-run only. No files will be created or modified."
  if [ "$MODE" = "competition" ] && [ "$ALLOW_INSECURE_LAN_COOKIE" != "true" ]; then
    echo "Note: real competition deployment needs --allow-insecure-lan-cookie for HTTP LAN usage or HTTPS cookie configuration."
  fi
  exit 0
fi

check_python_version
GENERATED_ADMIN_PASSWORD="false"
if [ -z "$ADMIN_PASSWORD" ]; then
  ADMIN_PASSWORD="$(env_get GATEWAY_BOOTSTRAP_ADMIN_PASSWORD || true)"
  if [ -z "$ADMIN_PASSWORD" ]; then
    if [ "$MODE" = "competition" ]; then
      ADMIN_PASSWORD="$(generate_secret 18)"
      GENERATED_ADMIN_PASSWORD="true"
    else
      ADMIN_PASSWORD="admin"
    fi
  fi
fi

SESSION_SECRET="$(env_get GATEWAY_SESSION_SECRET || true)"
if [ -z "$SESSION_SECRET" ]; then
  SESSION_SECRET="$(generate_secret 32)"
fi
CREDENTIAL_SECRET="$(env_get GATEWAY_CREDENTIAL_SECRET || true)"
if [ -z "$CREDENTIAL_SECRET" ]; then
  CREDENTIAL_SECRET="$(generate_secret 32)"
fi
COMPETITION_MODE="false"
if [ "$MODE" = "competition" ]; then
  COMPETITION_MODE="true"
fi

write_env_file
export GATEWAY_DATA_DIR="$DATA_DIR"
export GATEWAY_BOOTSTRAP_ADMIN_USERNAME="$ADMIN_USERNAME"
export GATEWAY_BOOTSTRAP_ADMIN_PASSWORD="$ADMIN_PASSWORD"
export GATEWAY_SESSION_SECRET="$SESSION_SECRET"
export GATEWAY_CREDENTIAL_SECRET="$CREDENTIAL_SECRET"
export GATEWAY_COMPETITION_MODE="$COMPETITION_MODE"
export GATEWAY_COOKIE_SECURE="false"
export GATEWAY_ALLOW_INSECURE_LAN_COOKIE="$ALLOW_INSECURE_LAN_COOKIE"

if [ ! -x "$VENV_PYTHON" ]; then
  python3 -m venv "$VENV_DIR"
fi

"$VENV_PYTHON" -m pip install --upgrade pip
"$VENV_PYTHON" -m pip install -e "${PROJECT_DIR}[test]"

if [ "$RUN_TESTS" = "true" ]; then
  "$VENV_PYTHON" -m pytest "${PROJECT_DIR}/tests"
fi

"$VENV_PYTHON" -c "from model_gateway.config import Settings; from model_gateway.database import init_db, ensure_bootstrap_admin; s=Settings(); s.validate_runtime(); s.ensure_directories(); init_db(s.db_path); ensure_bootstrap_admin(s.db_path, s.bootstrap_admin_username, s.bootstrap_admin_password)"

if [ "$GENERATED_ADMIN_PASSWORD" = "true" ]; then
  echo "Generated initial admin password. Save it now; it will not be shown again by this script:"
  echo "$ADMIN_PASSWORD"
fi

if [ "$NO_START" = "true" ]; then
  echo "Deployment complete. Start later with: scripts/run-linux.sh --host ${BIND_HOST} --port ${PORT}"
  exit 0
fi

exec "${PROJECT_DIR}/scripts/run-linux.sh" --host "$BIND_HOST" --port "$PORT"
