param(
  [ValidateSet("competition", "dev")]
  [string]$Mode = "competition",
  [Alias("Host")]
  [string]$BindHost = "0.0.0.0",
  [int]$Port = 8080,
  [string]$DataDir = "",
  [string]$AdminUsername = "admin",
  [string]$AdminPassword = "",
  [switch]$AllowInsecureLanCookie,
  [switch]$RunTests,
  [switch]$NoStart,
  [switch]$DryRun
)

$ErrorActionPreference = "Stop"
$ProjectDir = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$EnvFile = Join-Path $ProjectDir ".gateway.env"
$VenvDir = Join-Path $ProjectDir ".venv"
$VenvPython = Join-Path (Join-Path $VenvDir "Scripts") "python.exe"
if (-not $DataDir) {
  $DataDir = Join-Path $ProjectDir "data"
}

function New-GatewaySecret {
  param([int]$Bytes = 32)
  $buffer = New-Object byte[] $Bytes
  $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  try {
    $rng.GetBytes($buffer)
  } finally {
    $rng.Dispose()
  }
  return [Convert]::ToBase64String($buffer).TrimEnd("=").Replace("+", "-").Replace("/", "_")
}

function Read-GatewayEnv {
  param([string]$Path)
  $values = @{}
  if (-not (Test-Path $Path)) {
    return $values
  }
  foreach ($line in Get-Content $Path) {
    $trimmed = $line.Trim()
    if (-not $trimmed -or $trimmed.StartsWith("#")) {
      continue
    }
    $separator = $line.IndexOf("=")
    if ($separator -le 0) {
      continue
    }
    $values[$line.Substring(0, $separator).Trim()] = $line.Substring($separator + 1)
  }
  return $values
}

function Write-GatewayEnv {
  param(
    [string]$Path,
    [hashtable]$Values
  )
  $orderedKeys = @(
    "GATEWAY_DATA_DIR",
    "GATEWAY_BOOTSTRAP_ADMIN_USERNAME",
    "GATEWAY_BOOTSTRAP_ADMIN_PASSWORD",
    "GATEWAY_SESSION_SECRET",
    "GATEWAY_CREDENTIAL_SECRET",
    "GATEWAY_COMPETITION_MODE",
    "GATEWAY_COOKIE_SECURE",
    "GATEWAY_ALLOW_INSECURE_LAN_COOKIE"
  )
  $lines = @("# Generated by scripts/deploy-windows.ps1. Do not commit this file.")
  foreach ($key in $orderedKeys) {
    $lines += "$key=$($Values[$key])"
  }
  Set-Content -Path $Path -Value $lines -Encoding UTF8
}

function Import-GatewayEnvMap {
  param([hashtable]$Values)
  foreach ($key in $Values.Keys) {
    [Environment]::SetEnvironmentVariable($key, [string]$Values[$key], "Process")
  }
}

function Get-CompatiblePython {
  $candidates = @(
    @{ Exe = "py"; Args = @("-3.12"); Label = "py -3.12" },
    @{ Exe = "py"; Args = @("-3.11"); Label = "py -3.11" },
    @{ Exe = "py"; Args = @("-3.10"); Label = "py -3.10" },
    @{ Exe = "python"; Args = @(); Label = "python" }
  )
  foreach ($candidate in $candidates) {
    if (-not (Get-Command $candidate.Exe -ErrorAction SilentlyContinue)) {
      continue
    }
    $previousErrorActionPreference = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    try {
      & $candidate.Exe @($candidate.Args) -c "import sys; raise SystemExit(0 if sys.version_info >= (3, 10) else 1)" 1>$null 2>$null
      $candidateExitCode = $LASTEXITCODE
    } finally {
      $ErrorActionPreference = $previousErrorActionPreference
    }
    if ($candidateExitCode -eq 0) {
      return $candidate
    }
  }
  throw "Python 3.10 or newer is required. Install Python 3.10+ or make it available through the Windows py launcher."
}

if ($Mode -eq "competition" -and -not $AllowInsecureLanCookie -and -not $DryRun) {
  throw "Competition deployment over plain HTTP requires -AllowInsecureLanCookie. Use HTTPS with GATEWAY_COOKIE_SECURE=true for production-grade cookie transport."
}

$existing = Read-GatewayEnv -Path $EnvFile
$generatedAdminPassword = $false
if (-not $AdminPassword) {
  if ($existing.ContainsKey("GATEWAY_BOOTSTRAP_ADMIN_PASSWORD")) {
    $AdminPassword = [string]$existing["GATEWAY_BOOTSTRAP_ADMIN_PASSWORD"]
  } elseif ($Mode -eq "competition") {
    $AdminPassword = New-GatewaySecret -Bytes 18
    $generatedAdminPassword = $true
  } else {
    $AdminPassword = "admin"
  }
}

$sessionSecret = if ($existing.ContainsKey("GATEWAY_SESSION_SECRET")) { [string]$existing["GATEWAY_SESSION_SECRET"] } else { New-GatewaySecret -Bytes 32 }
$credentialSecret = if ($existing.ContainsKey("GATEWAY_CREDENTIAL_SECRET")) { [string]$existing["GATEWAY_CREDENTIAL_SECRET"] } else { New-GatewaySecret -Bytes 32 }
$envValues = @{
  GATEWAY_DATA_DIR = $DataDir
  GATEWAY_BOOTSTRAP_ADMIN_USERNAME = $AdminUsername
  GATEWAY_BOOTSTRAP_ADMIN_PASSWORD = $AdminPassword
  GATEWAY_SESSION_SECRET = $sessionSecret
  GATEWAY_CREDENTIAL_SECRET = $credentialSecret
  GATEWAY_COMPETITION_MODE = if ($Mode -eq "competition") { "true" } else { "false" }
  GATEWAY_COOKIE_SECURE = "false"
  GATEWAY_ALLOW_INSECURE_LAN_COOKIE = if ($AllowInsecureLanCookie) { "true" } else { "false" }
}

Write-Host "DeepRacer Model Gateway deployment"
Write-Host "Mode: $Mode"
Write-Host "Project: $ProjectDir"
Write-Host "Env file: $EnvFile"
Write-Host "Data dir: $DataDir"
Write-Host "Virtualenv: $VenvDir"
Write-Host "User URL: http://$BindHost`:$Port/login"
Write-Host "Admin URL: http://$BindHost`:$Port/admin/login"

if ($DryRun) {
  Write-Host "Dry-run only. No files will be created or modified."
  if ($Mode -eq "competition" -and -not $AllowInsecureLanCookie) {
    Write-Host "Note: real competition deployment needs -AllowInsecureLanCookie for HTTP LAN usage or HTTPS cookie configuration."
  }
  exit 0
}

$Python = Get-CompatiblePython
Write-GatewayEnv -Path $EnvFile -Values $envValues
Import-GatewayEnvMap -Values $envValues

if (-not (Test-Path $VenvPython)) {
  & $Python.Exe @($Python.Args) -m venv $VenvDir
}

& $VenvPython -m pip install --upgrade pip
& $VenvPython -m pip install -e "$ProjectDir[test]"

if ($RunTests) {
  & $VenvPython -m pytest (Join-Path $ProjectDir "tests")
}

& $VenvPython -c "from model_gateway.config import Settings; from model_gateway.database import init_db, ensure_bootstrap_admin; s=Settings(); s.validate_runtime(); s.ensure_directories(); init_db(s.db_path); ensure_bootstrap_admin(s.db_path, s.bootstrap_admin_username, s.bootstrap_admin_password)"

if ($generatedAdminPassword) {
  Write-Host "Generated initial admin password. Save it now; it will not be shown again by this script:"
  Write-Host $AdminPassword
}

if ($NoStart) {
  Write-Host "Deployment complete. Start later with: scripts\run-windows.ps1 -Host $BindHost -Port $Port"
  exit 0
}

& (Join-Path $PSScriptRoot "run-windows.ps1") -Host $BindHost -Port $Port
